### PR TITLE
Fix page cache to allow dynamic unique param

### PR DESCRIPTION
**Pull request by faishal**
This will allow developer to add `unique` based on query string or any dynamic conditions.

We can also add filter for the same.

### CODE REVIEW

**Comment by joehoyle** [comment]
Hmm it's not clear to me how this works. I'm not sure if this is conflating `get_ignore_query_params` with `unique`, as those two things are "opposites". `get_ignore_query_params` allows you to say `page doesn't need to be unique for these query params`. Is this intending to add a `unique` api in the `composer.json`, or is it just supporting people setting `unqiue` on the batcache global?

**Comment by roborourke** [comment]
@joehoyle we have a way to set both unique headers and ignored query vars via composer - this is addressing the ability to set them dynamically in code before Altis kicks in. You can't do conditional checks in `composer.json` essentially so this is to address that.

It isn't merging the unique and ignored query strings - just defaulting them both to empty arrays as keys on the `$batcache` global.

**Comment by roborourke** [comment]
Actually @faishal can you document how this would be used as well?

**Comment by joehoyle** [comment]
Ahh ok cool, so this is a regression for people who were usign `global $batcache` I support?

**Comment by roborourke** [comment]
Yep, exactly that

**Pull request merged**
