### PR TITLE
Update build container package versions

### PR DESCRIPTION
**Pull request by nathanielks**
This brings our docs up to date with the latest updates.

### CODE REVIEW

**Comment by nathanielks** [comment]
I think I got the labels right, feel free to edit as you please!

**Comment by rmccue** [comment]
FWIW, v1 is unsupported, and we have no clients left on v2, so we generally don't bother backporting those. :)

**Comment by nathanielks** [comment]
Hmm, I just checked the site and the old versions are still being displayed. Would you help with that, @rmccue ?

https://www.altis-dxp.com/resources/docs/cloud/build-scripts/

**Comment by roborourke** [comment]
Just need to update the marketing site it seems. Looks like there might be other work under way on the dev branch though. It’ll be updated to v5 in a week anyway which def has the changes

**Comment by nathanielks** [comment]
Bril, thanks @roborourke !

**Pull request merged**
