### PR TITLE
Ensure disallowed session handler class methods match parent class

### LINKED ISSUE #732: PHP Session Handler deprecation warnings for method implementations
I see the following output when running PHPCS against an Altis project running PHP 8.1 on both the command line and local server.

This is with Altis v14 as well.

Steps to reproduce:
1. Using PHPCS installed to the local project via the `humanmade/coding-standards` package run `vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true -q .`
2. Note the following deprecation warnings about Altis Cloud:

```
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::open($save_path, $session_name) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 20

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::open($save_path, $session_name) should either be compatible with SessionHandlerInterface::open(string $path, string $name): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 20
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 24

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::close() should either be compatible with SessionHandlerInterface::close(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 24
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::read($id) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 26

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::read($id) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 26
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::write($id, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 27

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::write($id, $data) should either be compatible with SessionHandlerInterface::write(string $id, string $data): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 27
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::destroy($id) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 25

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::destroy($id) should either be compatible with SessionHandlerInterface::destroy(string $id): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 25
PHP Deprecated:  Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 28

Deprecated: Return type of Altis\Cloud\Session_Handler\Disallowed_Session_Handler::gc($maxlifetime) should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/rob/projects/agbi/vendor/altis/cloud/inc/session_handler/class-disallowed-session-handler.php on line 28
```

- [ ] ...

### PR DESCRIPTION
**Pull request by roborourke**
Fixes #732

### CODE REVIEW

**Comment by roborourke** [comment]
@mikelittle this should only be backported as far as v12 I think as the union types require PHP 8.0

**Comment by mikelittle** [comment]
> @mikelittle this should only be backported as far as v12 I think as the union types require PHP 8.0

V12 still supports php7.4, though it is deprecated. So backporting that far would break.

**Review by mikelittle — CHANGES_REQUESTED** [review]
Some linter issues to be sorted.

**Review by roborourke — COMMENTED** [review]
I think one of these linter issues is due to linter bot being on PHP 7.1

**Review by mikelittle — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
