### PR TITLE
Document how to configure nginx to block a file

### PR DESCRIPTION
**Pull request by kadamwhite**
This could be reorganized to have more document hierarchy later on, but this example came up in Slack and having it spelled out explicitly may help future Altis developers. Snippet kindly provided by @nathanielks

### CODE REVIEW

**Comment by joehoyle** [comment]
Wondering if this will block the root file by that name, or all files in any dir of that name? Or -- which of those do you intend?

**Comment by nathanielks** [comment]
This should block all files with that name. Blocking the root would need a forward slash at the beginning. I gave that example, so I was assuming it'd be good to block all occurances!

**Comment by joehoyle** [comment]
Ok, I think we might be able to make the example description clearer about that, currently it says "if you have a local file in your repository you wish to explicitly block"

**Comment by kadamwhite** [comment]
@joehoyle Revised the prose & comment. Look OK?

**Comment by joehoyle** [comment]
Great stuff, thanks @kadamwhite

**Pull request merged**
