### PR TITLE
Update to cavalcade 2.0.0

### PR DESCRIPTION
**Pull request by roborourke**
Cavalcade 2.0.0 features the new pre flight filters, uses a more flexible `get_jobs_by_query()` method, better db indexes and better handling of the installation process.

### CODE REVIEW

**Comment by joehoyle** [comment]
What does it break in BC? (assuming something for the 2.0)

**Comment by roborourke** [comment]
@joehoyle shouldn’t break anything for any standard setup, the 2.0 was more of a reflection the scale of the change to the code base switching to using the filters.

**Comment by joehoyle** [comment]
Ok sounds good!

**Comment by joehoyle** [comment]
Is there a need for a new version of the Runner with this BTW?

**Comment by roborourke** [comment]
No the runner should be fine as is

**Pull request merged**
