### PR TITLE
Update AWS X-Ray to 1.2.5

### PR DESCRIPTION
**Pull request by rmccue**
Fixes metadata (https://github.com/humanmade/aws-xray/pull/56) and segment details in Query Monitor (https://github.com/humanmade/aws-xray/pull/51).

### CODE REVIEW

**Comment by joehoyle** [comment]
Think this should be 1.2.6 now?

**Comment by rmccue** [comment]
If you're on board with it, we can switch to the `~` requirement here instead

**Comment by joehoyle** [comment]
Yeah thikn that would be ok

**Comment by roborourke** [comment]
Added the `~` constraint.

**Pull request merged**
