### PR TITLE
Exclude ALB healthchecks from X-ray

### LINKED ISSUE #237: Exclude healthchecks from X-Ray
Healthcheck requests shouldn't be loaded in X-Ray, as they affect the statistics of request times, etc.

### PR DESCRIPTION
**Pull request by joehoyle**
Fixes #237

### CODE REVIEW

**Review by rmccue — APPROVED** [review]
Wondering if we should keep the data but change where it's recorded for our own internal debugging purposes. Seems like it might be useful occasionally.

**Comment by joehoyle** [comment]
The best option I think there would be to tag with another service name instead of the main app one, like `humanade-production-healthcheck`. However, I'm not sure it's worth it, I know it _can_ be useful once in a blue moon.

**Comment by rmccue** [comment]
Right, that's what I mean. We can handle in the future; if you think it's worth having, can you create a new issue to track that please?

**Comment by joehoyle** [comment]
Ok created in https://github.com/humanmade/altis-cloud/issues/246

**Pull request merged**
