### PR TITLE
Update plugin to adhere to humanmade/coding-standards

### PR DESCRIPTION
**Pull request by nathanielks**
Before I get to work on fixing the negative maxage bug we've encountered, I wanted to update the repo to be compliant with hm-linter. This updates the plugin to adhere to our coding standards, except in instances where it was simpler to ignore to maintain back-compat: Namespaces and changing the name of the batcache class.

### CODE REVIEW

**Comment by nathanielks** [comment]
Ah, I now see we include batcache directly instead of using our fork of the repo. I also see we ignore this whole directory from linting. I can still see value in adding these updates as my editor shows linting errors in my sidebar. It also makes it easier to fix formatting errors because I can run `phpcbf` on the whole file without worrying about breaking something.

**Comment by joehoyle** [comment]
I think instead of this we should move these to composer per #5, then (if we want) file these changes upstream. We’ll prob Amy need to add our forks to composer too to switch these to composer deps

**Comment by nathanielks** [comment]
@joehoyle 	got it 👍 	For clarification, can you clarify what you mean by "We’ll [probably] need to add our forks to composer too to switch these to composer deps?"  I'm not 100% sure how forks play into this. My understanding of what needs to happen is we need to take the packages currently in `plugins/` and `dropins/` and move them into their own repository (if it doesn't exist), add composer support, then publish on Packagist.

**Comment by joehoyle** [comment]
Yup exactly, though we already have repos for these: https://github.com/humanmade/batcache

**Comment by nathanielks** [comment]
Got it, thanks! I'll work on doing that 👍

**Pull request closed without merging**
