### PR TITLE
add note for log retention

### PR DESCRIPTION
**Pull request by owaincuvelier**

### CODE REVIEW

**Comment by mikelittle** [comment]
@owaincuvelier Did you mean to raise this against v18-branch? Would it be better as a PR against master, with labels added to backport to all the supported versions?

**Comment by mikelittle** [comment]
@owaincuvelier This change is good but, as per my comment, it aplies to all current versions. So the PR should be made against the master branch and the backport labels added for all the current versions.

**Comment by mikelittle** [comment]
@owaincuvelier I switched this to be against master, but some additional changes are showing up. I don't know if that is because your v18-branch was out of date. Or you need to rebase your branch against master.

**Comment by owaincuvelier** [comment]
@mikelittle my bad! I'll close this PR and just reopen it.

**Pull request closed without merging**
